### ISSUE TITLE
Can't build puppet

### ISSUE THREAD

**Issue by A-xis** [solarkennedy/puppet-on-openwrt#1]
Hi,

I'm trying to build puppet for openwrt from http://wiki.openwrt.org/doc/howto/easy.build for an Ubiquiti Pico2. I can't use your repo due ton an unsifisant space on the device :(

So, I have downloaded "https://github.com/solarkennedy/puppet-on-openwrt/tree/master/openwrt-makefiles" into "openwrt/attitude_adjustment/package". I have removed the old shadow package and added the new one using "make menuconfig"

When doing "make V=s":

Collected errors:
- satisfy_dependencies_for: Cannot satisfy the following dependencies for puppet:
-      libc \*  shadow-chage *
- pkg_run_script: package "puppet" postinst script returned status 2.
- opkg_configure: puppet.postinst returned 2.

Where are my error ? :(

**Comment by solarkennedy** [comment]
If you want I can build packages for your arch. You can also wait for
upstream to be accepted: http://patchwork.openwrt.org/patch/3672/

I don't quite understand, if you can't us my repo because of lack of flash,
then how will rebuilding your own package work?
It does look like you are missing the shadow-chage package. You can either
build that too or download it from download.openwrt.org snapshots dir.

In the end, it is very unlikely you will be able to run puppet on that
device, 32M ram and 8M flash just won't cut it. CFEngine might be a good
alternative?

**Comment by A-xis** [comment]
Hi,

We are working on the migration of all our wifi AP from OLLLDDDD Linksys WRT45G. We use puppet because this is already in place for our servers and computers :| .

**Comment by solarkennedy** [comment]
You can try, it doesn't run on my device that has 32M ram.
Is that device atheros? If not find your specific arch, you can try this to
meet the dependencies:
http://downloads.openwrt.org/snapshots/trunk/atheros/packages/shadow-chage_4.1.5.1-3_atheros.ipk

**Comment by A-xis** [comment]
Hello,

After some test, when doing make packge/puppet/compill it works.
When doing make without the puppet package, it works.
:|
the ubnt pico2 used the bullet M bin (the device refuse the pico2 bin)

**Comment by solarkennedy** [comment]
So, a ipkg was generated? 

If you are still having issues, can you pastebin some output?

**Comment by A-xis** [comment]
Hello

My .config is visible here : http://a-xis.fr/~openwrt/config

It compile as an ipkg. without errors, but i don't know why i can't integrate puppet in the binary image :(

Here is the output when trying to compiling with puppet integrated http://pastebin.com/gxkESxpD

**Comment by solarkennedy** [comment]
Please, I need some sort of error message to work on.
Are there any error messages when you try to install/run the puppet ipkg?

**Comment by A-xis** [comment]
Hi,

So, the output is : http://pastebin.com/gxkESxpD (with this .config http://a-xis.fr/~openwrt/config)

I think the problem is in the Makefile, in the block "define Package/puppet/postinst" but i'm not an expert in openwrt package

**Comment by A-xis** [comment]
Hi, here is a way for setting a new user and group on OpenWRT : https://forum.openwrt.org/viewtopic.php?pid=85197#p85197

**Comment by solarkennedy** [comment]
Yes, if you inspect the puppet makefile I use similar syntax to make the
puppet user/group. If you want to make your own you should edit the make
file and build a custom package.
