### ISSUE TITLE
puppet agent doesn't register with puppet master

### ISSUE THREAD

**Issue by m8ram** [solarkennedy/puppet-on-openwrt#2]
Hi,

After installing openwrt on my new TP-Link TL-WDR4300 and adding an external USB key to have sufficient storage to install puppet I tried to register it to my puppet server but no certificate request is shown on the puppet master.

Here's the output on the openwrt router (the agent):

```
root@OpenWrt:~# puppet agent --server=puppet --no-daemonize --verbose
Info: Creating a new SSL key for openwrt.lan
ruby: can't resolve symbol 'getipnodebyname'
```

(I added a line to /etc/hosts for now so puppet can be resolved to the IP address of my master.

However no signing request shows up on the master:

```
[m8ram@puppet ~]$ sudo puppet cert list 
[m8ram@puppet ~]$
```

I can't find any logs in /var/log/puppet so this is all the information I can provide right now.
What can I do to troubleshoot this?

Thanks in advance.

Bram

**Comment by m8ram** [comment]
https://dev.openwrt.org/ticket/9873 appears to describe what is needed to fix this.

The following ruby updates are required:
opkg install /tmp/libruby_1.9.3-p429-1_ar71xx.ipk /tmp/ruby-core_1.9.3-p429-1_ar71xx.ipk /tmp/ruby_1.9.3-p429-1_ar71xx.ipk /tmp/ruby-gems_1.9.3-p429-1_ar71xx.ipk

After that the agent is registered as expected!

**Comment by solarkennedy** [comment]
You got it.

This is probably one of the contributing factors to stopping it from being committed upstream, as it requires so many other things to be fixed first :( 
https://lists.openwrt.org/pipermail/openwrt-devel/2013-March/019268.html
