### ISSUE TITLE
unable to start puppet agent through puppet

### ISSUE THREAD

**Issue by m8ram** [solarkennedy/puppet-on-openwrt#5]
I've created the following module:

```
class ardarouter::service {
    service { "puppet":
        ensure     => running,
        hasstatus  => false,
        hasrestart => false,
        enable     => true,
    }
}
```

and applied that to my router node.
However when I run pupet agent manually to get it to start the service
it doesn't apply the change:

```
root@OpenWrt:~# ps w|grep puppet
26871 root      1492 S    grep puppet
root@OpenWrt:~# puppet agent --test
Info: Retrieving plugin
Info: Loading facts in /etc/puppet/lib/facter/concat_basedir.rb
Info: Loading facts in /etc/puppet/lib/facter/pe_version.rb
Info: Loading facts in /etc/puppet/lib/facter/facter_dot_d.rb
Info: Loading facts in /etc/puppet/lib/facter/ip6tables_version.rb
Info: Loading facts in /etc/puppet/lib/facter/iptables_persistent_version.rb
Info: Loading facts in /etc/puppet/lib/facter/root_home.rb
Info: Loading facts in /etc/puppet/lib/facter/puppet_vardir.rb
Info: Loading facts in /etc/puppet/lib/facter/iptables_version.rb
Info: Caching catalog for openwrt.lan
Info: Applying configuration version '1395577892'
Notice: Finished catalog run in 2.03 seconds
root@OpenWrt:~# ps w|grep puppet
27065 root      1492 S    grep puppet
```

Could this be because puppet considers itself "running" during the manual run?
The reason I suspect this is the output of puppet resource:

```
root@OpenWrt:~# puppet resource service puppet
service { 'puppet':
  ensure => 'running',
  enable => 'true',
}
```

Stopping the service by changing the manifest to ensure => stopped works.

**Comment by m8ram** [comment]
However I suspected the service would at least start at boot time but
it doesn't even though the init script is in place:

```
root@OpenWrt:~# ls -l /etc/rc.d/S70puppet
lrwxrwxrwx    1 root     root            16 Mar 23 12:17
/etc/rc.d/S70puppet -> ../init.d/puppet
root@OpenWrt:~# ps w |grep puppet
 1694 root      1492 S    grep puppet
```

Before the reboot I was able to start the service using the init script but now I get a ruby segmentation fault:

```
root@OpenWrt:~# /etc/init.d/puppet start
<internal:gem_prelude>:1: [BUG] Segmentation fault
ruby 1.9.3p429 (2013-05-15 revision 40747) [mips-linux]

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0010 b:0010 l:000009 d:000009 CFUNC  :require
c:0003 p:0021 s:0006 b:0006 l:000005 d:000005 TOP    <internal:gem_prelude>:1
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:000ac4 d:000ac4 TOP

-- Ruby level backtrace information ----------------------------------------
<internal:gem_prelude>:1:in `<compiled>'
<internal:gem_prelude>:1:in `require'

-- Other runtime information -----------------------------------------------

* Loaded script: /usr/bin/ruby

* Loaded features:

    0 enumerator.so
    1 /usr/lib/ruby/1.9/mips-linux/enc/encdb.so
    2 /usr/lib/ruby/1.9/mips-linux/enc/trans/transdb.so

* Process memory map:

00400000-00401000 r-xp 00000000 08:01 153        /usr/bin/ruby
00410000-00411000 rw-p 00000000 08:01 153        /usr/bin/ruby
00bb1000-00ca1000 rwxp 00000000 00:00 0          [heap]
77b74000-77b76000 r-xp 00000000 08:01 435
/usr/lib/ruby/1.9/mips-linux/enc/trans/transdb.so
77b76000-77b85000 ---p 00000000 00:00 0
77b85000-77b86000 rw-p 00001000 08:01 435
/usr/lib/ruby/1.9/mips-linux/enc/trans/transdb.so
77b86000-77b88000 r-xp 00000000 08:01 400
/usr/lib/ruby/1.9/mips-linux/enc/encdb.so
77b88000-77b97000 ---p 00000000 00:00 0
77b97000-77b98000 rw-p 00001000 08:01 400
/usr/lib/ruby/1.9/mips-linux/enc/encdb.so
77b99000-77b9a000 ---p 00000000 00:00 0
77b9a000-77c1e000 rw-p 00000000 00:00 0
77c1e000-77c74000 r-xp 00000000 1f:02 840        /lib/libuClibc-0.9.33.2.so
77c74000-77c83000 ---p 00000000 00:00 0
77c83000-77c84000 r--p 00055000 1f:02 840        /lib/libuClibc-0.9.33.2.so
77c84000-77c85000 rw-p 00056000 1f:02 840        /lib/libuClibc-0.9.33.2.so
77c85000-77c8a000 rw-p 00000000 00:00 0
77c8a000-77c9d000 r-xp 00000000 1f:02 836        /lib/libgcc_s.so.1
77c9d000-77cac000 ---p 00000000 00:00 0
77cac000-77cad000 rw-p 00012000 1f:02 836        /lib/libgcc_s.so.1
77cad000-77cc2000 r-xp 00000000 1f:02 782        /lib/libm-0.9.33.2.so
77cc2000-77cd1000 ---p 00000000 00:00 0
77cd1000-77cd2000 rw-p 00014000 1f:02 782        /lib/libm-0.9.33.2.so
77cd2000-77cd8000 r-xp 00000000 1f:02 847        /lib/libcrypt-0.9.33.2.so
77cd8000-77ce7000 ---p 00000000 00:00 0
77ce7000-77ce8000 rw-p 00005000 1f:02 847        /lib/libcrypt-0.9.33.2.so
77ce8000-77cf9000 rw-p 00000000 00:00 0
77cf9000-77cfc000 r-xp 00000000 1f:02 846        /lib/libdl-0.9.33.2.so
77cfc000-77d0b000 ---p 00000000 00:00 0
77d0b000-77d0c000 r--p 00002000 1f:02 846        /lib/libdl-0.9.33.2.so
77d0c000-77d0d000 rw-p 00003000 1f:02 846        /lib/libdl-0.9.33.2.so
77d0d000-77d10000 r-xp 00000000 08:01 174        /lib/librt-0.9.33.2.so
77d10000-77d20000 ---p 00000000 00:00 0
77d20000-77d21000 rw-p 00003000 08:01 174        /lib/librt-0.9.33.2.so
77d21000-77d33000 r-xp 00000000 08:01 173        /lib/libpthread-0.9.33.2.so
77d33000-77d43000 ---p 00000000 00:00 0
77d43000-77d44000 r--p 00012000 08:01 173        /lib/libpthread-0.9.33.2.so
77d44000-77d45000 rw-p 00013000 08:01 173        /lib/libpthread-0.9.33.2.so
77d45000-77d47000 rw-p 00000000 00:00 0
77d47000-77f01000 r-xp 00000000 08:01 138        /usr/lib/libruby.so.1.9.1
77f01000-77f11000 ---p 00000000 00:00 0
77f11000-77f15000 rw-p 001ba000 08:01 138        /usr/lib/libruby.so.1.9.1
77f15000-77f24000 rw-p 00000000 00:00 0
77f24000-77f2b000 r-xp 00000000 1f:02 845        /lib/ld-uClibc-0.9.33.2.so
77f38000-77f3a000 rw-p 00000000 00:00 0
77f3a000-77f3b000 r--p 00006000 1f:02 845        /lib/ld-uClibc-0.9.33.2.so
77f3b000-77f3c000 rw-p 00007000 1f:02 845        /lib/ld-uClibc-0.9.33.2.so
7f845000-7f866000 rwxp 00000000 00:00 0          [stack]
7fff7000-7fff8000 r-xp 00000000 00:00 0          [vdso]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Aborted
```

**Comment by m8ram** [comment]
This is on a TPLink WDR4300 (http://wiki.openwrt.org/toh/tp-link/tl-wdr4300)
with http://wiki.openwrt.org/toh/tp-link/tl-wdr4300 installed.

A USB key added in overlay mode to add the required storage for the puppet agent installation.

list of packages installed: http://pastebin.com/mHmczEAq

**Comment by solarkennedy** [comment]
So I guess there are two issues.

The first is the init script. If you do 

```
puppet resource service puppet --debug
```

I think you will find your suspicion is correct about it using ps:
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/service/openwrt.rb#L31

This is kinda in the nature of low-tech openwrt init scripts. A workaround is to set the "[pattern](http://docs.puppetlabs.com/references/latest/type.html#service-attribute-pattern)" to include the agent line, so puppet would do its own ps/grep for exactly the agent part.

Another work around is to simply not use the puppet service, and us it via cron (recommended).

A more permanent fix could be to add a status function to the init script, then you could set `hasstatus => true`. 

I've personally kinda given up on submitting patches to Openwrt for this, it doesn't generally seem to be accepted. I recommend one of the above workarounds.

**Comment by solarkennedy** [comment]
The second issue is the ruby segfault. I don't know what to think about that.

We are probably the only people using ruby with ulibc. (maybe)

I have no idea what to do about that there. I guess it is only segfaulting on the "agent" subcommand? (without -t)  I don't know.

A workaround for this might be to again, just use it via cron. This is the only method I personally use on openwrt and abroad.

**Comment by m8ram** [comment]
Sorry for the late reply, I have not been able to investigate this before today.
Anyway I completely reinstalled my router and installed all of the ruby packages from https://docs.google.com/file/d/0B54xzz44RpW6YlpaQXV3M2hTQVk/edit to address https://dev.openwrt.org/ticket/9873.  Then I installed puppet from your repository and I no longer get the segmentation fault.

However now I get a yaml warning:

```
root@OpenWrt:~# puppet resource user puppet
/usr/lib/ruby/1.9/yaml.rb:56:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
user { 'puppet':
  ensure  => 'present',
  comment => 'Puppet configuration management daemon',
  gid     => '1000',
  home    => '/var/lib/puppet',
  shell   => '/bin/ash',
  uid     => '1000',
}
```

I believe the segfault may have been the result of an incompatibility between some of the ruby packages you provided and the ones I installed later.  But it seems that there still is a compatibility issue between the two sources.
I installed libyaml from your sources and reinstalled all ruby packages as well as puppet but to no avail.
Any idea how to proceed from here?

Note despite this warning puppet agent starts and appears to apply the configuration.

Regards
Bram

**Comment by solarkennedy** [comment]
Yea the yaml thing is a "known" issue. (to me)

I haven't encountered something that breaks because of it, but also, because I don't forsee the openwrt maintainers accepting patches for the ruby stuff, I've kinda given up, and wait for the ticket you commented on: https://dev.openwrt.org/ticket/9873

But I wouldn't bring Puppet into the mix there. Just wait for someone to commit the openwrt ruby patches.

**Comment by m8ram** [comment]
OK, this can be closed then.
The ruby segmentation fault appears to have been a problem with my installation and running puppet as a daemon on this device requires more memory than it has available.
