### ISSUE TITLE
Is the project dead already ?

### ISSUE THREAD

**Issue by dynek** [solarkennedy/puppet-on-openwrt#7]
http://download.xkyle.com/openwrt/

Host Not Found

DNS error (the host name of the page you are looking for does not exist) or Server did not accept the connection.

Please check that the host name has been spelled correctly.

**Comment by solarkennedy** [comment]
Hmmmm... yea I stopped paying for hosting the binaries. :(

Let me figure something else out for that....

But in general, yes, the project is dead in the sense that the patches were never accepted upstream. The patches are here in case you want to compile it yourself.

**Comment by dynek** [comment]
crap -  I saw such an activity around this that I thought I would have it working in no time :-(

It really makes sense to be able to configure my openwrt devices using puppet.

**Comment by solarkennedy** [comment]
What hardware platform do you need binaries for?

**Comment by solarkennedy** [comment]
Eh, I take it back, this project is dead. I'm not going to support it :(

One big blocker is the exec type doesn't work right on the openwrt glibc (#6). This is a deal breaker.

Also, I am no longer eating my own dogfood here. I'll leave the patches here for posterity, and maybe someday I'll try _Again_ to get them upstream so binaries are available for everyone.

**Comment by dynek** [comment]
got it :-) no worries - just too bad your contribution wasn't taken into account.

would have definitely been a great addition to OpenWRT !
